# Site settings
title: Laksh Gupta
header-img: img/home-bg.jpg
#email: your-email@yourdomain.com
description: "A Blog for Some Stuff"
baseurl: ""
url: "http://lakshgupta.github.io"
twitter_username: lakshgupta_
github_username:  lakshgupta
#facebook_username:  lakshgupta

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
